### ISSUE TITLE
Disable migration execution timing

### ISSUE THREAD

**Issue by norkunas** [doctrine/migrations#1159]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

When migrating with `query-time` option set `DbalExecutor::executeResult` calculates the time with Stopwatch and outputs it, but when migrating without it the calculations still are executed but non printed. As I don't care on deploy how much time migrations took I'd say that it should not be calculated at all then. Maybe migrations would be executed faster? :)
Not sure the reason of this, but just want to start discussion. IMHO an option could be added to disable the calculations.

**Comment by greg0ire** [comment]
> Maybe migrations would be executed faster? :)

How likely do you think this would be? On one hand we have symfony/stopwatch, that makes no calls to the database or the filesystem, and on the other hand we are executing SQL queries, which involves going over the network to reach a database server.

> Not sure the reason of this

I think it was just simpler not to add more if statements, but the best way to figure this out is to try contributing this yourself.

> IMHO an option could be added to disable the calculations.

Why? This could be done based on `query-time`, couldn't it? No need for a new option IMO. Note that it would be simpler if `symfony/stopwatch` had a `Stopwatch` interface that could be implemented with a `NullStopwatch`. It doesn't, probably because this has never been needed.

**Comment by norkunas** [comment]
> This could be done based on `query-time`, couldn't it? No need for a new option IMO. 

Way better :)

**Comment by greg0ire** [comment]
IMO it's very unlikely to be worth it, but you are still welcome to give it a try, and if you do find a performance improvement, please open a pull request :slightly_smiling_face: 
Closing in the meantime.
