### ISSUE TITLE
Setting single migration as non-transaction broken

### ISSUE THREAD

**Issue by shadowhand** [doctrine/migrations#1166]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.1.3

#### Summary

When setting a single migration as non-transactional, the class setting is ignored and produces an error:

```
REATE INDEX CONCURRENTLY cannot run inside a transaction block             
```

This migration has:

```php
public function isTransactional(): bool
{
    return false;
}
```

#### Previous behavior

Migration class `isTransactional()` flag works as expected. Migration was working.

#### Current behavior

Migration class `isTransactional()` flag is ignored, resulting in a database error because the SQL must **NOT** be run inside a transaction.

#### How to reproduce

We are using Postgres, which has a `create index concurrently ...` expression. The `concurrently` flag cannot be run in a transaction, because it executes in a non-blocking way. So create a migration with:

```php
    public function up(Schema $schema): void
    {
        $createIndex = <<<SQL
         create index concurrently
        if not exists idx_user_name
                   on users (lower(last_name), lower(first_name))
        SQL;

        $this->addSql($createIndex);
    }

    public function down(Schema $schema): void
    {
        $dropIndex = <<<SQL
        drop index idx_user_name
        SQL;

        $this->addSql($dropIndex);
    }

    public function isTransactional(): bool
    {
        return false;
    }
```

This migration worked correctly in 3.1.2 and is broken in 3.1.3, I assume because of PR #1161.

**Comment by greg0ire** [comment]
@shadowhand I suspect `all-or-nothing` is configured to `true` in your setup… can you please show us your configuration?

**Comment by shadowhand** [comment]
@greg0ire you're correct:

```php
return [
    'table_storage' => [
        'table_name' => 'migrations',
        'version_column_name' => 'version',
        'version_column_length' => 191,
        'executed_at_column_name' => 'executed_at',
        'execution_time_column_name' => 'execution_time',
    ],
    'migrations_paths' => [
        'Acme\\Framework\\Migration' => 'src/Framework/Migration',
    ],
    'all_or_nothing' => true,
    'check_database_platform' => false,
];
```

This seems like a significant BC break though, given that `all-or-nothing` didn't conflict with per-migration `isTransactional: false` setting.

**Comment by greg0ire** [comment]
Thanks for confirming my hunch! I suppose you tried setting it to `false` and it fixed your issue.
Next step would be finding out what to expect when it's set to true and then one migration among the ones disallows transaction. A quick look at the docs yields nothing specific, so let's use our common sense instead. If I have 3 migrations, and this option and is enabled, and the last migrations forbids transaction, it cannot work.

We could trying figuring this out and silently disabling `all-or-nothing` in such cases, but IMO that's bad: we would let our user think they are using transactions when they are not; in fact it's unclear what our user is thinking, since they are using contradictory options.
I think we should instead let them know what the issue is, and how to fix it, by throwing an exception with a clear message as soon as possible.

When `all-or-nothing` is true, we should throw as soon as we know that a migration returns `false` in `isTransactional()`. The exception should point out the contradiction, and require the user explicitly the CLI option `--all-or-nothing=0` to override the configuration.

> This seems like a significant BC break though, given that all-or-nothing didn't conflict with per-migration isTransactional: false setting.

:thinking: it doesn't seem like a BC break to me, we are now trying to comply to what the configuration tells us, and IMO `all-or-nothing` should absolutely, strongly but, and that's what is missing here clearly conflict with per-migration `isTransactional: false` setting.

If we do what I suggest, we should also add note(s) in the documentation of `all-or-nothing` and/or `isTransactional`.

I think this could be implemented here: https://github.com/doctrine/migrations/blob/8d0c58655cf9d76462d00ec5dd099737e513e86d/lib/Doctrine/Migrations/DbalMigrator.php#L61-L69

We could add a new method to `MigrationPlanList` called `assertCompatibleWithAllOrNothing` that would throw as follows unless all migrations in the list are transactional:

```php
throw new \UnexpectedValueException(<<<'EXCEPTION'
    Context: trying to execute migrations in one transaction as per all-or-nothing configuration option
    Problem: at least transaction XXX is marked as non-transactional
    Solution: disable all-or-nothing in the configuration or from the CLI with --all-or-nothing=0
    EXCEPTION
);
```

@shadowhand @grachevko what do you think? If you agree with this, would either of you be willing to work on this?

**Comment by shadowhand** [comment]
`assertCompatibleWithAllOrNothing` seems like the ideal solution to me, I will work on a PR.

**Comment by shadowhand** [comment]
@greg0ire PR has been created.
