### ISSUE TITLE
Diff command generating unnecessary migration

### ISSUE THREAD

**Issue by KevinMarques** [doctrine/migrations#1434]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.7.4
| ORM | 3.2.0
| DBAL | 4.0.3
#### Summary

When executing `doctrine-migrations diff` command, it generates a migration even though the entity and the database correspond to each other on datetime_immutable defined field.

#### Current behavior

Diff command generates unnecessary migration over and over again when already in sync:
`$this->addSql('ALTER TABLE test_entity ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');`

If I change the entity column type to `'datetime'` instead of `'datetime_immutable'` then it works properly, but I need to use [the immutable type](https://www.doctrine-project.org/projects/doctrine-dbal/en/4.0/reference/types.html#datetime-immutable).

#### How to reproduce

Entity definition:
```
#[ORM\Entity]
#[ORM\Table(name: 'test_entity')]
class TestEntity
{
    #[ORM\Column(name: 'created_at', type: 'datetime_immutable')]
    private DateTimeImmutable $createdAt;
}
```

Execute:

1. `doctrine-migrations diff`
2. `doctrine-migrations migrate `
3. `doctrine-migrations diff`

#### Expected behavior

No migration generated when already in sync using the `datetime_immutable` type column.

**Comment by KevinMarques** [comment]
For others experiencing this problem, the solution is to first apply:
`COMMENT ON COLUMN test_entity.created_at IS ''`.

[These comments were removed in DBAL 4](https://www.doctrine-project.org/projects/doctrine-dbal/en/3.8/explanation/dc2type-comments.html) and were causing the issue.

**Comment by geoffroyp** [comment]
I would like to reopen this issue since I'm experiencing the same problem, but with mysql.

In the past, I used requiresSQLCommentHint() for some of my custom doctrine types. Now that this method has been removed, make:migration removes indeed the comment that was set in the past

BUT

...even after running the up() method of the migration, if I run make:migration again, these lines are generated again, and again, and again...

Any solution?
