### ISSUE TITLE
Data loss on table renaming.

### ISSUE THREAD

**Issue by ThePixelDeveloper** [doctrine/migrations#17]
With the feature `$schema->renameTable('old', 'new');` you end up losing your data due to how this function works.

Doctrine creates a new table with the old table definitions and then drops the old table. It fails to migrate the data into the new table. There are two solutions to this problem (1st one preferred):
1. Use the native statement (`RENAME TABLE old TO new`) [Documentation](http://dev.mysql.com/doc/refman/5.5/en/rename-table.html)
2. SELECT the old data into the new table.

Thoughts appreciated.

**Comment by catasoft** [comment]
5 years later, $schema->renameTable() still loses all data from source table.

**Comment by stof** [comment]
@catasoft the generated SQL is only migrating the schema. Migrating data is never guaranteed to be done properly by generated queries because this is impossible to guarantee without knowing your data structure (adding fields also requires populating them)

**Comment by stof** [comment]
and btw, this is exactly why the ``schema:update`` command is marked as being unsafe for prod: it does not give any way to tweak the SQL, while migrations do as you can do what you want with the migration after the initial generation (you can even start from scratch without generating any SQL btw)

**Comment by przemo-hemmersbach** [comment]
Hello. Can this issue be reopened.
`renameTable` is simply laying about what it does. It's true name is `dropAndCreateWithNewName`.
Because it looses data I think this deserves a bug classification. If renaming isn't possible `renameTable` should be considered for deprecation and removal from api.

As for possible fixes. Could `renameTable` be exteded to accept callback that is given enough data as arguments so that developer can manually migrate data? Such callback would be executed after `CREATE TABLE` and before `DROP TABLE`.

**Comment by alcaeus** [comment]
The issue is in DBAL, not in this library. Please file an issue at https://github.com/doctrine/dbal/issues if the issue persists, and please make sure to provide the SQL platform you are using as that's what's building the SQL required for the operation.
