### ISSUE TITLE
Allow the output of raw sql in MigrationDiffCommand

### ISSUE THREAD

**Issue by exi** [doctrine/migrations#206]
We would like to read our sql statements from separate sql files that correspond to schema versions.
For this it would be cool if we could export the generated sql to actual sql files or generate two separate files.

The generated php class could look like this:
```php
<?php

namespace Project\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150216132253 extends AbstractMigration
{
    public function up(Schema $schema) {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');
        $this->addSql(file_get_contents(__DIR__ . '/Version20150216132253_up.sql'));
    }
    public function down(Schema $schema) {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');
        $this->addSql(file_get_contents(__DIR__ . '/Version20150216132253_down.sql'));
    }
}
```
With the separate sql files containing the actual sql statements.

At the moment this is impossible because the diff command provides no extension points to hook into.
Do you think that there would be a chance to integrate this if i posted a pull request?

**Comment by TomasVotruba** [comment]
:+1:

**Comment by mikeSimonson** [comment]
The problem with that kind of approach is that you need to find a way to split your file content per sql query statement. Because no sql driver allow you to pass more than one sql query per call (for security and consistency reasons).
And there is no easy way to do that at all, you will literally need to implement an sql query parser.

In the end you will be better off doing that manually and putting the content in the your migration file or just writing a script that will just pass all your query through a pipe to mysql.
