### ISSUE TITLE
isInteractive ?

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/migrations#216]
Hi,

At some point there was a discussion about the use of ```$this->isInteractive()``` [here](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/ExecuteCommand.php#L85) instead of the ```$input->getOption('no-interaction')``` call.

What would be the difference ?
Shouldn't we use ```$this->isInteractive()||$input->getOption('no-interaction')``` ?

**Comment by mikeSimonson** [comment]
@stof

**Comment by stof** [comment]
not ``$this->isInteractive()`` (which does not exist) but ``$input->isInteractive()``

The difference is that ``no-interaction`` is not a command-level option. It is an application-level option which is *one* of the way to choose whether the input is interactive or no. But the application has additional logic (in some cases, it is able to know that your input has no way to be interactive).

As a general rule, application-level options should not be accessed directly by commands, because they are not in control of them (and applications may be refactored and stop defining them btw). The same is true for instance for ``--verbose`` vs ``$output->getVerbosity()`` (which is set based on *multiple* options)

**Comment by aivus** [comment]
Should be closed after #231
