### ISSUE TITLE
some special chars breaks the addSql() execution.

### ISSUE THREAD

**Issue by feyyazesat** [doctrine/migrations#316]
This query gives me following error
UPDATE pj_country SET currency_code = 'UYU', currency_name = 'Peso', currency_symbol = '$U' WHERE iso = 'UY' LIMIT 1;

Migration 20150801043632 failed during Execution. Error Notice: Undefined variable: U
                                                           
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined variable: U

**Comment by chrisguitarguy** [comment]
It's not migration's, it's all of PHP. PHP sees `$U` as a variable because the string is [double quoted](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.double) and tries to resolve it.

You can add a backslash before the dollar sign to stop your error from happening: `currency_symbol = '\$U'`

**Comment by feyyazesat** [comment]
thanks @chrisguitarguy aggh I missed that.
