### ISSUE TITLE
problem with order of schema and custom SQL

### ISSUE THREAD

**Issue by cordoval** [doctrine/migrations#352]
```php
$toSchema = clone $fromSchema;
            $this->migration->$direction($toSchema);
            $this->addSql($fromSchema->getMigrateToSql($toSchema, $this->platform));
```

so when adding SQL after the alter for a table it will just not listen and not fill the fields with data

**Comment by cordoval** [comment]
closing upon confirming or finding a work around

**Comment by sstok** [comment]
This problems is also described in http://www.jcfiala.net/blog/2014/08/29/using-doctrine-migrations-part-2-adding-data-migration

When you update the Schema in `up()` using the Object oriented approach (instead of running raw SQL queries) then any custom SQL you add will be placed before the schema update.

So the custom SQL should be applied *after* the schema updating query.
Instead of calling addSql() you would need prependSql() or something.

I wonder if this is would be a BC break as this current method is horrible broken :monkey_face:

**Comment by cordoval** [comment]
i gave you that link :blush: ok, but that approach does not work

should i reopen? i moved on and don't care too much about this tbh, but yeah it shocked me a bit

**Comment by mikeSimonson** [comment]
@sstok The behavior described in the blog post you posted is really weird and should be corrected.

@cordoval What were you trying to do exactly in your first code example ?

**Comment by stof** [comment]
If you want to apply some changes after the schema updates are applied, you can do it in ``postUp``. The case where you use the Schema object to perform changes is a perfect use case for ``postUp`` (even though I think using the Schema object is actually a mistake as it makes you loose most of the control over your schema change)

> So the custom SQL should be applied after the schema updating query.

This would be a huge BC break, so -1 on this

> Instead of calling addSql() you would need prependSql() or something.

This would be very confusing, because prepending would run queries in the opposite order than the one you see when reading the source code (otherwise, you are not really prepending)

**Comment by mikeSimonson** [comment]
@cordoval For now the "right" way or "least painfull" way of doing that is to put the change of the schema and addSql should be in 2 differents migrations. Mostly because Mysql doesn't support DDL statement in transaction. It will autoclose it and if something goes wrong then it's a pain to revert that half migrated migrations.
