### ISSUE TITLE
Decide what the expected usage of addSql should be

### ISSUE THREAD

**Issue by stof** [doctrine/migrations#369]
#362 changed the behavior of ``addSql``. @mikeSimonson and me started a discussion in https://github.com/doctrine/migrations/commit/d393217244b059be8be98250c6f65d2044434996#commitcomment-13883728 about whether this makes sense, and what should be the behavior of the library.
This issue is meant to be the place where this discussion continues to be more visible

**Comment by farzadghanei** [comment]
> IMO, a better way would be to forbid using addSql in post* methods 

@stof As a user of the library I agree this is one of the solutions. If I was warned that `addSql` calls are not allowed in `post*`, I would have understood this is the desired behavior by design, and not a "missing feature".

The idea behind pull request #362 was to add this missing feature.
I agree it introduced a bug though, and pull request #368 fixes that bug (and another bug that has not shown up yet, which is the return value of `execute`).

However both requests are assuming using `addSql` in `post*` is a missing feature. If the library has no intend to provide such behavior, then there is no need for them.

**Comment by mikeSimonson** [comment]
So,

Sorry for the delay in my answer.

It's a bit tricky to decide what it should do but here are the different point of view that I see.

Allow the use of addSql in pre and post:
  - consistent approach (all the method with the same signature have the same capabilities)
  - use the infrastructure in place to manage the sql

Against:
  - impossible to revert the code added there

Right now, I have a hard time finding a good argument to go one way or the other.

I also don't understand why the clone of the schema object is done after the pre method is run. Is it a way to prevent people to modify the schema object in the pre method and only allow it's use for read ?

Maybe the sanest right now is prevent any modification in pre and post method and add documentation to describe the intended use a little bit better?

What do you think ? @stof

**Comment by stof** [comment]
@mikeSimonson I never used the Schema object to perform changes actually (this is a fragile approach as it does not give the possibility to review the changes being done in the DB or to migrate data, and I almost always need to add some queries in the middle to migrate data)

**Comment by mikeSimonson** [comment]
Not using the schema is always the safest approach indeed.
