### ISSUE TITLE
Don't use schema when running migrations

### ISSUE THREAD

**Issue by mRoca** [doctrine/migrations#375]
Hi,

I'm working on a big Oracle database, and the `OracleSchemaManager::createSchema` method can take more than 3 hours to run... 

As this method is used in the `Version::execure` methd, I can't use the current lib to run migrations for this project. I actually generate them with a virtualized environment containing only concerned tables, and use an [updated version of the `Version` class](https://github.com/mRoca/migrations/commit/5a7d260fe52ba0b87dc6f6e927293364515d20a6) that don't use Schema when running migrations on the true DB, but it is a ugly hack... And refactor more code will break BC...

Is there another way to do that ? Or a `--dont-use-schema` option for the `migrations:migrate` command ?

**Comment by stof** [comment]
I plan to finish https://github.com/doctrine/migrations/pull/323 soon

**Comment by mRoca** [comment]
Oups, didn't see it. Sorry and thanks :)

**Comment by mikeSimonson** [comment]
So right now the simplest way to fix your issue is to pass a connection to doctrine migrations where you have filtered all the tables. The build of the schema object will then be a noop.

$connection->getConfiguration()->setFilterSchemaAssetsExpression('/^(?!.*)$/');

You can create a connection with that filter and use it only for the migrations.
