### ISSUE TITLE
doctrine migration does not detect change from  integer to guid , and generate empty migrations

### ISSUE THREAD

**Issue by allan-simon** [doctrine/migrations#381]
I've recently applied to my code the following patch 

```
-     * @ORM\Column(name="id", type="integer")
+     * @ORM\Column(name="id", type="guid")
      * @ORM\Id
-     * @ORM\GeneratedValue(strategy="AUTO")
+     * @ORM\GeneratedValue(strategy="UUID")
```

I've run a migration using the doctrine migration bundle, an empty migration is generated but nothing more 

I'm using postgresql as my database  and the version 1.1.0 of this lib

**Comment by allan-simon** [comment]
if it may help, it seems to happen because said property is in a Trait

**Comment by mikeSimonson** [comment]
@allan-simon Hi, not sure what the guid type map to in your configuration.
In any case it's either normal because in your configuration the guid map to an integer and thus there is no change from the database point of view.
Or it maps to something else and then it's a bug, but it's a bug in the dbal layer as it is what we use to generate all the sql.
Here is the tracker for the dbal.
http://www.doctrine-project.org/jira/projects/DBAL/issues/DBAL-1081?filter=allopenissues

Thanks @allan-simon

**Comment by allan-simon** [comment]
hello, thanks I'm going to open a bug in their tracker then, as i'm not using any special mapping, guid being a predefined type by doctrine , which according to their documentation should map to UUID type in postgresql. Especially as once I've moved the column declaration from a trait to the class itself, it is now correctly detected. 
Anyway thanks for your precision :)
