### ISSUE TITLE
Add option to change proxiesTargetDir of ocramius/ProxyManager

### ISSUE THREAD

**Issue by DaveLister007** [doctrine/migrations#485]
Right now, library creates default proxy manager without any means of changing its configuration.  Not even by subclassing some classes and overiding functionality because of private properties

That is problem mainly because that library uses temp directory to store its proxy files. It defaults to whateverr sys_get_temp_dir() returns, so it usually woks with default config, but on some systems it doesn't and need to be configured to custom directory.

**Comment by mikeSimonson** [comment]
@DaveLister007 To my knowledge, because we are using the eval strategy, the only case were the sys_get_temp_dir will be loaded is if you have eval disabled.

You can already override the evalStrategy by passing a schema provider containing the desired ProxyManager configuration to the Version class.
If you want to do so you will also have to create your Migrations Configuration class and use your schemaProvider in the registerMigrations method of the Migrations Configuration class.

**Comment by DaveLister007** [comment]
I would have to override Configuration::registerMigration, and pass own schemaProvider to version class. But I can't do that, because registerMigration method need access to $this->migrations, which is private.
Anyway, even if this would be possible, it seems kinda hacky, more native way would be nicer.

**Comment by mikeSimonson** [comment]
@DaveLister007 PR welcomed

**Comment by DaveLister007** [comment]
I just got to me what you meant by eval strategy. Somehow it wasnt using eval in my case, even though I didn't disabled it. It was crashing when trying to access temp directory outside of open_basedir restriction, hence crashing.
Im not sure why, will need to investigate more, but if eval works, there is no need to change this directory. I guess you can close this.
