### ISSUE TITLE
Diff drops all tables because of schema_filter

### ISSUE THREAD

**Issue by qpautrat** [doctrine/migrations#531]
Hello,

Why do we resolve the table name by removing the namespace (or the schema) [there](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/DiffCommand.php#L99) ?

In my use case, when I want to do a migration, I filter all schemas in my database except one it matters from the configuration: `schema_filter: '/^some_schema./'`.

It works well until the `DiffCommand` drops all tables which does not match the filter. But it can not match whatever happens because we remove the schema from the table name in `resolveTableName` function.

Why ? Do I misunderstand something ?

Thank you.

**Comment by mikeSimonson** [comment]
Due to incompatibilities between some database vendors, we have to extract the name of table like that.
If you still want to exclude all the tables from a database, you will have to pull all the tables name in the schema_filter expression.

Also note that trying to use one migration configuration to manage multiple databases at once will bite you back sooner or later.
Prefer having multiple migrations configuration and migrations classes for each databases.

Cheers

**Comment by alextech** [comment]
Came across this discussion while debugging PostgreSQL migrations diff. Doesn't this behavior make migration diff not work at all, even out of the box with no custom configurations?
When I run migration:diff, even when no changes are made to entity mappers, doctrine always thinks that all existing tables should be dropped and tries to recreate them with namespace prefix. Cycle continues, as on all further scan the namespace prefix is dropped causing a cycle

    $this->addSql('CREATE TABLE public.clients (id INT NOT NULL, ...');
    $this->addSql('DROP TABLE clients');
