### ISSUE TITLE
Compatibility PHP 7.0

### ISSUE THREAD

**Issue by laurentPereira** [doctrine/migrations#547]
Can we have a branch or tags with the last release compatible PHP 7.0 ?

Thanks

**Comment by haco28** [comment]
👍

**Comment by jewome62** [comment]
Can you precise your version of doctrine-migrations ?

**Comment by laurentPereira** [comment]
Symfony 2.8.*
PHP 7.0.*
Doctrine 2.5.*
and 
doctrine-migration 1.6-dev (dev-master)

Since this commit, I can't update because the requirement is on PHP 7.1

 https://github.com/doctrine/migrations/commit/9f307aa9b61f1321cde98422bcd8d88f1ca3fbed#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by haco28** [comment]
the problem is that i use in my composer the dev-master version.
recently i upgrade my version of PHP (5.6 to 7.0) and upgrade all version of symfony, doctrine,...
but any version of doctrine-migration work with my configuration. it needs php 5 or 7.1 and any version is compatible with 7.0. the only one solution is to upgrade my symfony to 3.0 (but i can't the project is too big) or to roolback to php 5.6

**Comment by stof** [comment]
well, version 1.6 of doctrine-migrations will indeed require PHP 7.1. Latest release compatible with PHP 7.0 is 1.5

**Comment by Majkl578** [comment]
Latest release is 1.5.0 compatible with 5.6+. Using dev-master is at your own risk.

> I can't update because the requirement is on PHP 7.1

You should update your PHP version, 7.0 is not only _incomplete_ in terms of feature-set (missing primarily nullables), it will also be EOL'd in december this year.

**Comment by alcaeus** [comment]
For compatibility with PHP < 7.1, use the 1.5 branch. We'll backport **security fixes** as necessary. Features will be in 1.6 only which requires PHP 7.1.
