### ISSUE TITLE
New release for Migration Events

### ISSUE THREAD

**Issue by sergiughf** [doctrine/migrations#553]
Hey guys,

the current release is  v1.5.0 for this project and that contains code that is about 1 years old. Would it kindly be possible to make a new release so we have access to the Migration Events?

I would really appreciate if this would be possible!

**Comment by mikeSimonson** [comment]
Will happen first week of October as I will be at PHPNorthWest.

**Comment by sergiughf** [comment]
That sounds great! Thanks a lot!

**Comment by sergiughf** [comment]
Hey @mikeSimonson any updates? :)

**Comment by Jean85** [comment]
Can we push the update? We're currently having issues with the bundle, see https://github.com/doctrine/DoctrineMigrationsBundle/issues/207

**Comment by sergiughf** [comment]
It's been 1 month since the PHPNorthWest conference, could we have some updates please?

**Comment by Jean85** [comment]
In the meantime, the bundle was fixed with a hack: https://github.com/doctrine/DoctrineMigrationsBundle/pull/213

**Comment by alcaeus** [comment]
> It's been 1 month since the PHPNorthWest conference, could we have some updates please?

I'm in the process of finishing up the 1.6 milestone: https://github.com/doctrine/migrations/milestone/10. There's an issue with absolute paths in custom templates (fixed by #569) and the custom template needs to be applied to the diff command as well (see #566). Apart from that, we're good to go and I'm trying to wrap up late this week or on the weekend.

**Comment by alcaeus** [comment]
1.6.0 has been released, closing here.
