### ISSUE TITLE
Dependency to ocramius/proxy-manager forces php7.2

### ISSUE THREAD

**Issue by nrobinaubertin** [doctrine/migrations#587]
Hi,
I saw in the changelog that doctrine/migrations follows semantic versioning.
Doctrine/migrations depends on ocramius/proxy-manager:
```
"ocramius/proxy-manager": "^1.0|^2.0"
```
But since version 2.2, ocramius/proxy-manager [dropped support for php7.1](https://github.com/Ocramius/ProxyManager/blob/master/CHANGELOG.md).

Is it okay to have this kind of changes while following semantic versioning ?
Or should doctrine/migrations change his dependency to something like:
```
"ocramius/proxy-manager": "^1.0|^2.0 <2.2"
```

**Comment by alcaeus** [comment]
This is fine: composer will install 2.1 as long as you’re not running PHP 7.1.

**Comment by nrobinaubertin** [comment]
Ah okay, thanks for the quick reply !

**Comment by stof** [comment]
this is perfectly valid regarding semantic versioning, because Composer takes requirements into account when resolving deps, and this includes the PHP requirement.

So you only need to make sure that Composer is resolving deps for the right PHP version (the easiest way being to use the same PHP version than your prod, but otherwise Composer can also be configured to override the PHP version used for resolution)

**Comment by nrobinaubertin** [comment]
In fact, I had this issue because I generated a lock file being on php7.2 and the server is on php7.1.
So following @stof advice, I added
```
"config": {
    "platform": {
        "php": "7.1"
    }
}
```
in my composer.json.
Thanks for your help !
