### ISSUE TITLE
Mark classes internal that are internal

### ISSUE THREAD

**Issue by jwage** [doctrine/migrations#710]
There really isn't much that the outside should be depending on in this library/tool so mark everything as @internal that nobody should be depending on.

**Comment by stof** [comment]
well, I would say that the `Tools/Console` aprt should not be considered as internal, otherwise DoctrineMigrationsBundle reusing these commands to register them directly in the Symfony CLI would have to be considered as invalid (from the bundle perspective, we need to be able to rely on backward compatibility for these parts in non-major releases, and that means not being internal). 
The Configuration part should also be considered public API (even the built-in runner still relies on receiving a configuration)

**Comment by jwage** [comment]
Yes, the commands, configuration, etc. wouldn't be considered internal.

**Comment by stof** [comment]
well, the initial description says `mark everything as @internal`

**Comment by jwage** [comment]
Updated the description to be more accurate.
