### ISSUE TITLE
Order of version class execution not the same between V1 and V2

### ISSUE THREAD

**Issue by tifabien** [doctrine/migrations#789]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | Upgrade 1.0 > 2.0

#### Summary

During my upgrade v1 -> v2 I had an issue related to Migration class names.

#### Previous behavior

In v1 we could name migration classes as we wanted (e.g. VersionEpicDev.php). This class was executed after all classes named for exemple Version20190101....php

#### Current behavior

In v2.0 because we cast Version names as integer, this is no more the case.
EpicDev is executed at first.

#### How to reproduce

Create 2 Version classes (Version010000.php and VersionEpicDev.php) then execute the migration:migrate command. You'll see that the order of execution is not the same between v1 and v2.

**Comment by jwage** [comment]
Interesting. This behavior in 1.x was not intentional. The fact that they executed at the end is just coincidental. The version names need to be dates/integers so that we can properly determine order in a defined and reliable way. I am not sure if we have anything to change or fix here other than documenting this behavior difference. What do you think?

**Comment by tifabien** [comment]
I agree that we should add a small note on this in the documentation.
I updated my side version names in order to have the same execution order between 1.x and 2.x
Thanks for your clarification !
