### ISSUE TITLE
[RFC] Automatically skip migrations

### ISSUE THREAD

**Issue by grachevko** [doctrine/migrations#963]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I have two databases with different schemas. After generating migration i need manualy add skip instruction to it, or on execute migration it will try to apply to both databases and it will fail on a one of it.
Like this
```php 
$this->skipIf(0 !== strpos($this->connection->getDatabase(), 'landlord'), 'landlord only');
$this->skipIf(0 !== strpos($this->connection->getDatabase(), 'tenant'), 'tenant only');
```

Automatically add this skip can be through custom template, but for it doesn't contain placeholder for database name.
So, could we add this placeholder, or maybe another more better solution?

**Comment by goetas** [comment]
It is not clear to me what is here the feature request. Can you clarify please? (from your description it seems that what you want already works...)

**Comment by grachevko** [comment]
For now it works only if manually add `skiIf` after doctrine::diff generate migration.
RFC is about automate adding `skipIf` to `up` and `down`. 
I can add `skipIf` to custom_template, but still need to manually edit which database must no be skipped. Because of now in temlate doesn't exists placeholder like `<database>`

**Comment by TomHAnderson** [comment]
@grachevko I think you're just doing it wrong.  I've worked with multiple databases each with their own distinct schemas and migrations.  So this advice comes from experience:

Generate separate migrations for each database.  The Doctrine migrations comes as a `.phar` file so you are not limited to any integration to any particular framework in order to create migrations.

If you are using the orm schema tool to diff your databases to create migrations do it on a per-object manager basis and don't intermingle your schema.  I mean, that's just plain wrong IMHO.

Instead of using the framework integration create shell scripts to execute the migrations for each database independently.

**Comment by grachevko** [comment]
@TomHAnderson not much clear. Ofcourse i'm already use two separate command to generate and separate command to migrate. But for now it put all migrations to one directory. When i run migrate for first database it also use migration for second. And second migration command use migration for first database.
You suggest separate folder for migrations per database? This make sense. 
Maybe will be good idea to wait release of 3.0 with feature "Multiple namespaces and paths are allowed" and try something on top of it. I want separate migrations per bounded context, but for now not clear how it will be with multiply connections.

**Comment by TomHAnderson** [comment]
Create separate configs for each database using the .phar file
You're over thinking it.

Good luck.

**Comment by goetas** [comment]
I think that the approach explained in https://github.com/doctrine/DoctrineMigrationsBundle/issues/311#issuecomment-610021324 can solve your usecase.

I see that here the feature request is not clear, thus I'm closing it. 

If you can specify the exact change request, expected inputs and outcomes, I can certainly re open the ticket.
